# Generated by Django 4.0.3 on 2022-05-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_patient_name', models.TextField(default="First patient's name", max_length=25)),
                ('last_patient_name', models.TextField(default="Last patient's name", max_length=30)),
                ('first_doctor_name', models.TextField(default="First doctor's name", max_length=25)),
                ('last_doctor_name', models.TextField(default="Last doctor's name", max_length=30)),
                ('visit_date', models.DateField(default=None)),
                ('visit_slot', models.TimeField(default=None)),
                ('patient_id', models.IntegerField(default=0)),
                ('doctor_id', models.IntegerField(default=0)),
            ],
        ),
    ]
